/**
 * Campus360 Application Constants
 */

const ROLES = {
  ADMIN: 'ADMIN',
  HOD: 'HOD',
  FACULTY: 'FACULTY',
  STUDENT: 'STUDENT'
};

const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT'
};

const COMPLAINT_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

const FEE_STATUS = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  PARTIAL: 'PARTIAL'
};

const EXAM_TYPE = {
  INTERNAL: 'INTERNAL',
  MIDTERM: 'MIDTERM',
  PRACTICAL: 'PRACTICAL',
  FINAL: 'FINAL'
};

const ROOM_TYPE = {
  CLASSROOM: 'CLASSROOM',
  LAB: 'LAB',
  SEMINAR_HALL: 'SEMINAR_HALL',
  AUDITORIUM: 'AUDITORIUM'
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

module.exports = {
  ROLES,
  ATTENDANCE_STATUS,
  COMPLAINT_STATUS,
  FEE_STATUS,
  EXAM_TYPE,
  ROOM_TYPE,
  USER_STATUS
};
